import os
from flask import Flask, jsonify, request

#import pag1 as pag1
from yahooquery import Ticker
import json


app = Flask(__name__)


@app.route('/')
def nao_entre_em_panico():
    if request.headers.get('Authorization') == '42':
        return jsonify({"42": "a resposta para a vida, o universo e tudo mais"})
    return jsonify({"message": "Não entre em pânico!"})

@app.route('/dados')
def dados_acao():

    codigo = request.args.get('codigo')
    nome_do_ativo = str(codigo + '.SA').upper()
    df = Ticker(nome_do_ativo,country='Brazil')
    time = df.history( period='max')
    time = time.tail(300).reset_index().round(2)
    time['date_string'] = time['date'].astype(str).str.replace('-','-')
    time = time[['symbol','date_string','date','high','volume','close','low','open','adjclose']]
    time.columns=['codigo','date','date_long','high','volume','close','low','open','adjclose']
    time['codigo'] = time['codigo'].astype(str).str.replace('.SA','')

    result = time.to_json(orient="records")
    parsed = json.loads(result)

    #return '''<h1>O código é: {}</h1>'''.format(codigo)
    #return jsonify({'Dados para graficos' : f'{parsed}'})
    #return jsonify(result)
    return jsonify(parsed)

@app.route('/lista')
def lista_de_para():

    parsed= [{'code': 'BTTL3', 'name': 'Battistella Adm Participacoes S.A.'},
 {'code': 'MMAQ3', 'name': 'Minasmaquinas S.A.'},
 {'code': 'MMAQ4', 'name': 'Minasmaquinas S.A.'},
 {'code': 'WLMM3', 'name': 'Wlm Part. E Comercio De Maquinas E Veiculos S.A.'},
 {'code': 'WLMM4', 'name': 'Wlm Part. E Comercio De Maquinas E Veiculos S.A.'},
 {'code': 'AZEV3', 'name': 'Azevedo E Travassos S.A.'},
 {'code': 'AZEV4', 'name': 'Azevedo E Travassos S.A.'},
 {'code': 'SOND3', 'name': 'Sondotecnica Engenharia Solos S.A.'},
 {'code': 'SOND5', 'name': 'Sondotecnica Engenharia Solos S.A.'},
 {'code': 'SOND6', 'name': 'Sondotecnica Engenharia Solos S.A.'},
 {'code': 'TCNO3', 'name': 'Tecnosolo Engenharia S.A.'},
 {'code': 'TCNO4', 'name': 'Tecnosolo Engenharia S.A.'},
 {'code': 'ETER3', 'name': 'Eternit S.A.'},
 {'code': 'HAGA3', 'name': 'Haga S.A. Industria E Comercio'},
 {'code': 'HAGA4', 'name': 'Haga S.A. Industria E Comercio'},
 {'code': 'PTBL3', 'name': 'Pbg S/A'},
 {'code': 'MILS3', 'name': 'Mills Estruturas E Servicos De Engenharia S.A.'},
 {'code': 'TASA3', 'name': 'Taurus Armas S.A.'},
 {'code': 'TASA4', 'name': 'Taurus Armas S.A.'},
 {'code': 'MTSA3', 'name': 'Metisa Metalurgica Timboense S.A.'},
 {'code': 'MTSA4', 'name': 'Metisa Metalurgica Timboense S.A.'},
 {'code': 'STTR3', 'name': 'Stara S.A. - Industria De Implementos Agricolas'},
 {'code': 'AERI3',
  'name': 'Aeris Ind. e Com. de Equip. Geração de Energia S.A.'},
 {'code': 'BDLL3', 'name': 'Bardella S.A. Industrias Mecanicas'},
 {'code': 'BDLL4', 'name': 'Bardella S.A. Industrias Mecanicas'},
 {'code': 'EALT3', 'name': 'Electro Aco Altona S.A.'},
 {'code': 'EALT4', 'name': 'Electro Aco Altona S.A.'},
 {'code': 'FRIO3', 'name': 'Metalfrio Solutions S.A.'},
 {'code': 'INEP3', 'name': 'Inepar S.A. Industria E Construcoes'},
 {'code': 'INEP4', 'name': 'Inepar S.A. Industria E Construcoes'},
 {'code': 'KEPL3', 'name': 'Kepler Weber S.A.'},
 {'code': 'NORD3', 'name': 'Nordon Industrias Metalurgicas S.A.'},
 {'code': 'PTCA11', 'name': 'Pratica Klimaquip Industria E Comercio SA'},
 {'code': 'PTCA3', 'name': 'Pratica Klimaquip Industria E Comercio SA'},
 {'code': 'ROMI3', 'name': 'Industrias Romi S.A.'},
 {'code': 'SHUL3', 'name': 'Schulz S.A.'},
 {'code': 'SHUL4', 'name': 'Schulz S.A.'},
 {'code': 'WEGE3', 'name': 'Weg S.A.'},
 {'code': 'EMBR3', 'name': 'Embraer S.A.'},
 {'code': 'FRAS3', 'name': 'Fras-Le S.A.'},
 {'code': 'MWET3', 'name': 'Wetzel S.A.'},
 {'code': 'MWET4', 'name': 'Wetzel S.A.'},
 {'code': 'POMO3', 'name': 'Marcopolo S.A.'},
 {'code': 'POMO4', 'name': 'Marcopolo S.A.'},
 {'code': 'RAPT3', 'name': 'Randon S.A. Implementos E Participacoes'},
 {'code': 'RAPT4', 'name': 'Randon S.A. Implementos E Participacoes'},
 {'code': 'RCSL3', 'name': 'Recrusul S.A.'},
 {'code': 'RCSL4', 'name': 'Recrusul S.A.'},
 {'code': 'RSUL3', 'name': 'Metalurgica Riosulense S.A.'},
 {'code': 'RSUL4', 'name': 'Metalurgica Riosulense S.A.'},
 {'code': 'TUPY3', 'name': 'Tupy S.A.'},
 {'code': 'ALPK3',
  'name': 'Allpark Empreendimentos Participacoes Servicos S.A'},
 {'code': 'ATMP3', 'name': 'Atma Participacoes S.A.'},
 {'code': 'BBML3', 'name': 'Bbm Logistica S.A.'},
 {'code': 'CARD3', 'name': 'Csu Cardsystem S.A.'},
 {'code': 'DTCY3', 'name': 'Dtcom - Direct To Company S.A.'},
 {'code': 'DTCY4', 'name': 'Dtcom - Direct To Company S.A.'},
 {'code': 'FLEX3', 'name': 'Flex Gestao De Relacionamentos S.A.'},
 {'code': 'PRNR3', 'name': 'Priner Servicos Industriais S.A.'},
 {'code': 'SEQL3', 'name': 'Sequoia Logistica E Transportes S.A'},
 {'code': 'VLID3', 'name': 'Valid Solucoes S.A.'},
 {'code': 'ANHB', 'name': 'Conc Sist Anhang-Bandeirant S.A. Autoban'},
 {'code': 'CCRO3', 'name': 'Ccr S.A.'},
 {'code': 'CRTE', 'name': 'Conc Rio-Teresopolis S.A.'},
 {'code': 'ECOR3', 'name': 'Ecorodovias Infraestrutura E Logistica S.A.'},
 {'code': 'TPIS3', 'name': 'Tpi - Triunfo Particip. E Invest. S.A.'},
 {'code': 'AGRU',
  'name': 'Conc. do Aeroporto Internacional de Guarulhos S.A.'},
 {'code': 'IVPR', 'name': 'Investimentos E Particip. Em Infra S.A. - Invepar'},
 {'code': 'PSVM11', 'name': 'Porto Sudeste V.M. S.A.'},
 {'code': 'STBP3', 'name': 'Santos Brasil Participacoes S.A.'},
 {'code': 'WSON33', 'name': 'Wilson Sons Ltd.'},
 {'code': 'AZUL4', 'name': 'Azul S.A.'},
 {'code': 'GOLL4', 'name': 'Gol Linhas Aereas Inteligentes S.A.'},
 {'code': 'FRRN', 'name': 'Rumo Malha Norte S.A.'},
 {'code': 'MRSA', 'name': 'Mrs Logistica S.A.'},
 {'code': 'RAIL3', 'name': 'Rumo S.A.'},
 {'code': 'RLOG3', 'name': 'Cosan Logistica S.A.'},
 {'code': 'VSPT3', 'name': 'Ferrovia Centro-Atlantica S.A.'},
 {'code': 'VSPT4', 'name': 'Ferrovia Centro-Atlantica S.A.'},
 {'code': 'HBSA3', 'name': 'Hidrovias Do Brasil S.A.'},
 {'code': 'LOGN3', 'name': 'Log-In Logistica Intermodal S.A.'},
 {'code': 'LUXM3', 'name': 'Trevisa Investimentos S.A.'},
 {'code': 'LUXM4', 'name': 'Trevisa Investimentos S.A.'},
 {'code': 'JSLG3', 'name': 'Jsl S.A.'},
 {'code': 'TGMA3', 'name': 'Tegma Gestao Logistica S.A.'},
 {'code': 'CNSY3', 'name': 'Cinesystem S.A.'},
 {'code': 'ALGT', 'name': 'Algar Telecom S.A.'},
 {'code': 'OIBR3', 'name': 'Oi S.A.'},
 {'code': 'OIBR4', 'name': 'Oi S.A.'},
 {'code': 'TELB3', 'name': 'Telec Brasileiras S.A. Telebras'},
 {'code': 'TELB4', 'name': 'Telec Brasileiras S.A. Telebras'},
 {'code': 'TIMS3', 'name': 'Tim S.A.'},
 {'code': 'VIVT3', 'name': 'Telefonica Brasil S.A'},
 {'code': 'VIVT4', 'name': 'Telefonica Brasil S.A'},
 {'code': 'LEVE3', 'name': 'Mahle-Metal Leve S.A.'},
 {'code': 'MYPK3', 'name': 'Iochpe Maxion S.A.'},
 {'code': 'PLAS3', 'name': 'Plascar Participacoes Industriais S.A.'},
 {'code': 'MGLU3', 'name': 'Magazine Luiza S.A.'},
 {'code': 'VVAR3', 'name': 'Via Varejo S.A.'},
 {'code': 'BTOW3', 'name': 'B2w - Companhia Digital'},
 {'code': 'CNTO3', 'name': 'Grupo Sbf SA'},
 {'code': 'LAME3', 'name': 'Lojas Americanas S.A.'},
 {'code': 'LAME4', 'name': 'Lojas Americanas S.A.'},
 {'code': 'LJQQ3', 'name': 'Lojas Quero-Quero S/A'},
 {'code': 'PETZ3', 'name': 'Pet Center Comercio E Participacoes S.A.'},
 {'code': 'SLED3', 'name': 'Saraiva Livreiros S.A.'},
 {'code': 'SLED4', 'name': 'Saraiva Livreiros S.A.'},
 {'code': 'AMAR3', 'name': 'Marisa Lojas S.A.'},
 {'code': 'ARZZ3', 'name': 'Arezzo Industria E Comercio S.A.'},
 {'code': 'CEAB3', 'name': 'Cea Modas S.A.'},
 {'code': 'CGRA3', 'name': 'Grazziotin S.A.'},
 {'code': 'CGRA4', 'name': 'Grazziotin S.A.'},
 {'code': 'GUAR3', 'name': 'Guararapes Confeccoes S.A.'},
 {'code': 'LLIS3', 'name': 'Restoque Comercio E Confeccoes De Roupas S.A.'},
 {'code': 'LREN3', 'name': 'Lojas Renner S.A.'},
 {'code': 'SOMA3', 'name': 'Grupo De Moda Soma S.A.'},
 {'code': 'AVLL11', 'name': 'Alphaville S.A.'},
 {'code': 'AVLL3', 'name': 'Alphaville S.A.'},
 {'code': 'CALI3', 'name': 'Construtora Adolpho Lindenberg S.A.'},
 {'code': 'CALI4', 'name': 'Construtora Adolpho Lindenberg S.A.'},
 {'code': 'CRDE3', 'name': 'Cr2 Empreendimentos Imobiliarios S.A.'},
 {'code': 'CURY3', 'name': 'Cury Construtora E Incorporadora S.A.'},
 {'code': 'CYRE3', 'name': 'Cyrela Brazil Realty S.A.Empreend E Part'},
 {'code': 'DIRR3', 'name': 'Direcional Engenharia S.A.'},
 {'code': 'EVEN3', 'name': 'Even Construtora E Incorporadora S.A.'},
 {'code': 'EZTC3', 'name': 'Ez Tec Empreend. E Participacoes S.A.'},
 {'code': 'GFSA3', 'name': 'Gafisa S.A.'},
 {'code': 'HBOR3', 'name': 'Helbor Empreendimentos S.A.'},
 {'code': 'INNT3', 'name': 'Inter Construtora E Incorporadora S.A.'},
 {'code': 'JFEN3', 'name': 'Joao Fortes Engenharia S.A.'},
 {'code': 'JHSF3', 'name': 'Jhsf Participacoes S.A.'},
 {'code': 'LAVV3', 'name': 'Lavvi Empreendimentos Imobiliários S.A.'},
 {'code': 'MDNE3', 'name': 'Moura Dubeux Engenharia S/A'},
 {'code': 'MELK3', 'name': 'Melnick Desenvolvimento Imobiliário S.A.'},
 {'code': 'MRVE3', 'name': 'Mrv Engenharia E Participacoes S.A.'},
 {'code': 'MTRE3',
  'name': 'Mitre Realty Empreendimentos E Participacoes S.A.'},
 {'code': 'PDGR3', 'name': 'Pdg Realty S.A. Empreend E Participacoes'},
 {'code': 'PLPL3', 'name': 'Plano & Plano Desenvolvimento Imobiliário S.A.'},
 {'code': 'RDNI3', 'name': 'Rni Negocios Imobiliarios S.A.'},
 {'code': 'RSID3', 'name': 'Rossi Residencial S.A.'},
 {'code': 'TCSA3', 'name': 'Tecnisa S.A.'},
 {'code': 'TEND3', 'name': 'Construtora Tenda S.A.'},
 {'code': 'TRIS3', 'name': 'Trisul S.A.'},
 {'code': 'VIVR3', 'name': 'Viver Incorporadora E Construtora S.A.'},
 {'code': 'LCAM3', 'name': 'Cia Locacao Das Americas'},
 {'code': 'MOVI3', 'name': 'Movida Participacoes Sa'},
 {'code': 'MSRO3', 'name': 'Maestro Locadora De Veiculos S.A.'},
 {'code': 'RENT3', 'name': 'Localiza Rent A Car S.A.'},
 {'code': 'SMLS3', 'name': 'Smiles Fidelidade S.A.'},
 {'code': 'ANIM3', 'name': 'Anima Holding S.A.'},
 {'code': 'BAHI3', 'name': 'Bahema Educacao S.A.'},
 {'code': 'COGN3', 'name': 'Cogna Educacao S.A.'},
 {'code': 'SEER3', 'name': 'Ser Educacional S.A.'},
 {'code': 'YDUQ3', 'name': 'Yduqs Participacoes S.A.'},
 {'code': 'HOOT3', 'name': 'Hoteis Othon S.A.'},
 {'code': 'HOOT4', 'name': 'Hoteis Othon S.A.'},
 {'code': 'BKBR3',
  'name': 'Bk Brasil Operacao E Assessoria A Restaurantes SA'},
 {'code': 'MEAL3', 'name': 'International Meal Company Alimentacao S.A.'},
 {'code': 'MNDL3', 'name': 'Mundial S.A. - Produtos De Consumo'},
 {'code': 'TECN3', 'name': 'Technos S.A.'},
 {'code': 'VIVA3', 'name': 'Vivara Participacoes S.A'},
 {'code': 'ALPA3', 'name': 'Alpargatas S.A.'},
 {'code': 'ALPA4', 'name': 'Alpargatas S.A.'},
 {'code': 'CAMB3', 'name': 'Cambuci S.A.'},
 {'code': 'GRND3', 'name': 'Grendene S.A.'},
 {'code': 'VULC3', 'name': 'Vulcabras/Azaleia S.A.'},
 {'code': 'CATA3', 'name': 'Cia Industrial Cataguases'},
 {'code': 'CATA4', 'name': 'Cia Industrial Cataguases'},
 {'code': 'CEDO3', 'name': 'Cia Fiacao Tecidos Cedro Cachoeira'},
 {'code': 'CEDO4', 'name': 'Cia Fiacao Tecidos Cedro Cachoeira'},
 {'code': 'CTKA3', 'name': 'Karsten S.A.'},
 {'code': 'CTKA4', 'name': 'Karsten S.A.'},
 {'code': 'CTNM3', 'name': 'Cia Tecidos Norte De Minas Coteminas'},
 {'code': 'CTNM4', 'name': 'Cia Tecidos Norte De Minas Coteminas'},
 {'code': 'CTSA3', 'name': 'Cia Tecidos Santanense'},
 {'code': 'CTSA4', 'name': 'Cia Tecidos Santanense'},
 {'code': 'CTSA8', 'name': 'Cia Tecidos Santanense'},
 {'code': 'DOHL3', 'name': 'Dohler S.A.'},
 {'code': 'DOHL4', 'name': 'Dohler S.A.'},
 {'code': 'ECPR3', 'name': 'Empresa Nac Com Redito Part S.A.Encorpar'},
 {'code': 'ECPR4', 'name': 'Empresa Nac Com Redito Part S.A.Encorpar'},
 {'code': 'PTNT3', 'name': 'Pettenati S.A. Industria Textil'},
 {'code': 'PTNT4', 'name': 'Pettenati S.A. Industria Textil'},
 {'code': 'SGPS3', 'name': 'Springs Global Participacoes S.A.'},
 {'code': 'TEKA3', 'name': 'Teka-Tecelagem Kuehnrich S.A.'},
 {'code': 'TEKA4', 'name': 'Teka-Tecelagem Kuehnrich S.A.'},
 {'code': 'TXRX11', 'name': 'Textil Renauxview S.A.'},
 {'code': 'TXRX3', 'name': 'Textil Renauxview S.A.'},
 {'code': 'TXRX4', 'name': 'Textil Renauxview S.A.'},
 {'code': 'HGTX3', 'name': 'Cia Hering'},
 {'code': 'TFCO4', 'name': 'Track & Field Co S.A.'},
 {'code': 'WHRL3', 'name': 'Whirlpool S.A.'},
 {'code': 'WHRL4', 'name': 'Whirlpool S.A.'},
 {'code': 'UCAS3', 'name': 'Unicasa Industria De Moveis S.A.'},
 {'code': 'HETA3', 'name': 'Hercules S.A. Fabrica De Talheres'},
 {'code': 'HETA4', 'name': 'Hercules S.A. Fabrica De Talheres'},
 {'code': 'SMFT3', 'name': 'Smartfit Escola De Ginastica E Danca S.A.'},
 {'code': 'BMKS3', 'name': 'Bicicletas Monark S.A.'},
 {'code': 'ESTR3', 'name': 'Manufatura De Brinquedos Estrela S.A.'},
 {'code': 'ESTR4', 'name': 'Manufatura De Brinquedos Estrela S.A.'},
 {'code': 'AHEB3', 'name': 'Sao Paulo Turismo S.A.'},
 {'code': 'AHEB5', 'name': 'Sao Paulo Turismo S.A.'},
 {'code': 'AHEB6', 'name': 'Sao Paulo Turismo S.A.'},
 {'code': 'SHOW3', 'name': 'T4f Entretenimento S.A.'},
 {'code': 'CVCB3', 'name': 'Cvc Brasil Operadora E Agencia De Viagens S.A.'},
 {'code': 'AGRO3', 'name': 'Brasilagro - Cia Bras De Prop Agricolas'},
 {'code': 'APTI3', 'name': 'Siderurgica J. L. Aliperti S.A.'},
 {'code': 'APTI4', 'name': 'Siderurgica J. L. Aliperti S.A.'},
 {'code': 'FRTA3', 'name': 'Pomifrutas S/A'},
 {'code': 'SLCE3', 'name': 'Slc Agricola S.A.'},
 {'code': 'TESA3', 'name': 'Terra Santa Agro S.A.'},
 {'code': 'BSEV3', 'name': 'Biosev S.A.'},
 {'code': 'SMTO3', 'name': 'Sao Martinho S.A.'},
 {'code': 'CAML3', 'name': 'Camil Alimentos S.A.'},
 {'code': 'JOPA3', 'name': 'Josapar-Joaquim Oliveira S.A. - Particip'},
 {'code': 'JOPA4', 'name': 'Josapar-Joaquim Oliveira S.A. - Particip'},
 {'code': 'MDIA3', 'name': 'M.Dias Branco S.A. Ind Com De Alimentos'},
 {'code': 'ODER3', 'name': 'Conservas Oderich S.A.'},
 {'code': 'ODER4', 'name': 'Conservas Oderich S.A.'},
 {'code': 'BAUH3', 'name': 'Excelsior Alimentos S.A.'},
 {'code': 'BAUH4', 'name': 'Excelsior Alimentos S.A.'},
 {'code': 'BEEF3', 'name': 'Minerva S.A.'},
 {'code': 'BRFS3', 'name': 'Brf S.A.'},
 {'code': 'JBSS3', 'name': 'Jbs S.A.'},
 {'code': 'MNPR3', 'name': 'Minupar Participacoes S.A.'},
 {'code': 'MRFG3', 'name': 'Marfrig Global Foods S.A.'},
 {'code': 'ABEV3', 'name': 'Ambev S.A.'},
 {'code': 'CRFB3', 'name': 'Atacadao S.A.'},
 {'code': 'PCAR3', 'name': 'Cia Brasileira De Distribuicao'},
 {'code': 'GMAT3', 'name': 'Grupo Mateus S.A.'},
 {'code': 'BOBR3', 'name': 'Bombril S.A.'},
 {'code': 'BOBR4', 'name': 'Bombril S.A.'},
 {'code': 'NTCO3', 'name': 'Natura &Co Holding S.A.'},
 {'code': 'ALSO3', 'name': 'Aliansce Sonae Shopping Centers S.A.'},
 {'code': 'BRML3', 'name': 'Br Malls Participacoes S.A.'},
 {'code': 'BRPR11', 'name': 'Br Properties S.A.'},
 {'code': 'BRPR3', 'name': 'Br Properties S.A.'},
 {'code': 'CCPR3', 'name': 'Cyrela Commercial Propert S.A. Empr Part'},
 {'code': 'CORR3', 'name': 'Correa Ribeiro S.A. Comercio E Industria'},
 {'code': 'CORR4', 'name': 'Correa Ribeiro S.A. Comercio E Industria'},
 {'code': 'GSHP3', 'name': 'General Shopping E Outlets Do Brasil S.A.'},
 {'code': 'HBTS3', 'name': 'Cia Habitasul De Participacoes'},
 {'code': 'HBTS5', 'name': 'Cia Habitasul De Participacoes'},
 {'code': 'HBTS6', 'name': 'Cia Habitasul De Participacoes'},
 {'code': 'IGBR3', 'name': 'Igb Eletronica S/A'},
 {'code': 'IGTA3', 'name': 'Iguatemi Empresa De Shopping Centers S.A'},
 {'code': 'JPSA3', 'name': 'Jereissati Participacoes S.A.'},
 {'code': 'LOGG3', 'name': 'Log Commercial Properties'},
 {'code': 'MNZC', 'name': 'Terminal Garagem Menezes Cortes S.A.'},
 {'code': 'MULT3', 'name': 'Multiplan - Empreend Imobiliarios S.A.'},
 {'code': 'SCAR3', 'name': 'Sao Carlos Empreend E Participacoes S.A.'},
 {'code': 'BBRK3', 'name': 'Brasil Brokers Participacoes S.A.'},
 {'code': 'LPSB3', 'name': 'Lps Brasil - Consultoria De Imoveis S.A.'},
 {'code': 'MOAR3', 'name': 'Monteiro Aranha S.A.'},
 {'code': 'PEAB3', 'name': 'Cia Participacoes Alianca Da Bahia'},
 {'code': 'PEAB4', 'name': 'Cia Participacoes Alianca Da Bahia'},
 {'code': 'SIMH3', 'name': 'Simpar S.A.'},
 {'code': 'ABCB4', 'name': 'Bco Abc Brasil S.A.'},
 {'code': 'BAZA3', 'name': 'Bco Amazonia S.A.'},
 {'code': 'BBAS11', 'name': 'Bco Brasil S.A.'},
 {'code': 'BBAS12', 'name': 'Bco Brasil S.A.'},
 {'code': 'BBAS3', 'name': 'Bco Brasil S.A.'},
 {'code': 'BBDC3', 'name': 'Bco Bradesco S.A.'},
 {'code': 'BBDC4', 'name': 'Bco Bradesco S.A.'},
 {'code': 'BEES3', 'name': 'Banestes S.A. - Bco Est Espirito Santo'},
 {'code': 'BEES4', 'name': 'Banestes S.A. - Bco Est Espirito Santo'},
 {'code': 'BGIP3', 'name': 'Bco Estado De Sergipe S.A. - Banese'},
 {'code': 'BGIP4', 'name': 'Bco Estado De Sergipe S.A. - Banese'},
 {'code': 'BIDI11', 'name': 'Banco Inter S.A.'},
 {'code': 'BIDI3', 'name': 'Banco Inter S.A.'},
 {'code': 'BIDI4', 'name': 'Banco Inter S.A.'},
 {'code': 'BMEB3', 'name': 'Bco Mercantil Do Brasil S.A.'},
 {'code': 'BMEB4', 'name': 'Bco Mercantil Do Brasil S.A.'},
 {'code': 'BMGB4', 'name': 'Banco Bmg S.A.'},
 {'code': 'BMIN3', 'name': 'Bco Mercantil De Investimentos S.A.'},
 {'code': 'BMIN4', 'name': 'Bco Mercantil De Investimentos S.A.'},
 {'code': 'BNBR3', 'name': 'Bco Nordeste Do Brasil S.A.'},
 {'code': 'BPAC11', 'name': 'Bco Btg Pactual S.A.'},
 {'code': 'BPAC3', 'name': 'Bco Btg Pactual S.A.'},
 {'code': 'BPAC5', 'name': 'Bco Btg Pactual S.A.'},
 {'code': 'BPAN11', 'name': 'Bco Pan S.A.'},
 {'code': 'BPAN4', 'name': 'Bco Pan S.A.'},
 {'code': 'BPAR3', 'name': 'Bco Estado Do Para S.A.'},
 {'code': 'BRIV3', 'name': 'Bco Alfa De Investimento S.A.'},
 {'code': 'BRIV4', 'name': 'Bco Alfa De Investimento S.A.'},
 {'code': 'BRSR3', 'name': 'Bco Estado Do Rio Grande Do Sul S.A.'},
 {'code': 'BRSR5', 'name': 'Bco Estado Do Rio Grande Do Sul S.A.'},
 {'code': 'BRSR6', 'name': 'Bco Estado Do Rio Grande Do Sul S.A.'},
 {'code': 'BSLI3', 'name': 'Brb Bco De Brasilia S.A.'},
 {'code': 'BSLI4', 'name': 'Brb Bco De Brasilia S.A.'},
 {'code': 'IDVL3', 'name': 'Bco Indusval S.A.'},
 {'code': 'IDVL4', 'name': 'Bco Indusval S.A.'},
 {'code': 'ITSA3', 'name': 'Itausa Investimentos Itau S.A.'},
 {'code': 'ITSA4', 'name': 'Itausa Investimentos Itau S.A.'},
 {'code': 'ITUB3', 'name': 'Itau Unibanco Holding S.A.'},
 {'code': 'ITUB4', 'name': 'Itau Unibanco Holding S.A.'},
 {'code': 'PINE3', 'name': 'Bco Pine S.A.'},
 {'code': 'PINE4', 'name': 'Bco Pine S.A.'},
 {'code': 'RPAD3', 'name': 'Alfa Holdings S.A.'},
 {'code': 'RPAD5', 'name': 'Alfa Holdings S.A.'},
 {'code': 'RPAD6', 'name': 'Alfa Holdings S.A.'},
 {'code': 'SANB11', 'name': 'Bco Santander (brasil) S.A.'},
 {'code': 'SANB3', 'name': 'Bco Santander (brasil) S.A.'},
 {'code': 'SANB4', 'name': 'Bco Santander (brasil) S.A.'},
 {'code': 'CRIV3', 'name': 'Financeira Alfa S.A.- Cred Financ E Invs'},
 {'code': 'CRIV4', 'name': 'Financeira Alfa S.A.- Cred Financ E Invs'},
 {'code': 'FNCN3', 'name': 'Finansinos S.A.- Credito Financ E Invest'},
 {'code': 'MERC3', 'name': 'Mercantil Brasil Financ S.A. C.F.I.'},
 {'code': 'MERC4', 'name': 'Mercantil Brasil Financ S.A. C.F.I.'},
 {'code': 'APER3', 'name': 'Alper Consultoria E Corretora De Seguros S.A.'},
 {'code': 'WIZS3', 'name': 'Wiz Solucoes E Corretagem De Seguros S.A.'},
 {'code': 'BBSE3', 'name': 'BB Seguridade Participacoes S.A.'},
 {'code': 'BRGE11', 'name': 'Consorcio Alfa De Administracao S.A.'},
 {'code': 'BRGE12', 'name': 'Consorcio Alfa De Administracao S.A.'},
 {'code': 'BRGE3', 'name': 'Consorcio Alfa De Administracao S.A.'},
 {'code': 'BRGE5', 'name': 'Consorcio Alfa De Administracao S.A.'},
 {'code': 'BRGE6', 'name': 'Consorcio Alfa De Administracao S.A.'},
 {'code': 'BRGE7', 'name': 'Consorcio Alfa De Administracao S.A.'},
 {'code': 'BRGE8', 'name': 'Consorcio Alfa De Administracao S.A.'},
 {'code': 'CSAB3', 'name': 'Cia Seguros Alianca Da Bahia'},
 {'code': 'CSAB4', 'name': 'Cia Seguros Alianca Da Bahia'},
 {'code': 'IRBR3', 'name': 'Irb - Brasil Resseguros S.A.'},
 {'code': 'PSSA3', 'name': 'Porto Seguro S.A.'},
 {'code': 'SULA11', 'name': 'Sul America S.A.'},
 {'code': 'SULA3', 'name': 'Sul America S.A.'},
 {'code': 'SULA4', 'name': 'Sul America S.A.'},
 {'code': 'GPIV33', 'name': 'Gp Investments, Ltd.'},
 {'code': 'PDTC3', 'name': 'Padtec Holding S.A.'},
 {'code': 'PPLA11', 'name': 'Ppla Participations Ltd.'},
 {'code': 'BOAS3', 'name': 'Boa Vista Serviços S.A.'},
 {'code': 'B3SA3', 'name': 'B3 S.A. - Brasil'},
 {'code': 'CIEL3', 'name': 'Cielo S.A.'},
 {'code': 'CTBA', 'name': 'Prefeitura Municipal De Curitiba'},
 {'code': 'MCRJ', 'name': 'Município Do Rio De Janeiro'},
 {'code': 'PMSP', 'name': 'Prefeitura Municipal De Sao Paulo'},
 {'code': 'MTIG3', 'name': 'Metalgrafica Iguacu S.A.'},
 {'code': 'MTIG4', 'name': 'Metalgrafica Iguacu S.A.'},
 {'code': 'DTEX3', 'name': 'Duratex S.A.'},
 {'code': 'EUCA3', 'name': 'Eucatex S.A. Industria E Comercio'},
 {'code': 'EUCA4', 'name': 'Eucatex S.A. Industria E Comercio'},
 {'code': 'KLBN11', 'name': 'Klabin S.A.'},
 {'code': 'KLBN3', 'name': 'Klabin S.A.'},
 {'code': 'KLBN4', 'name': 'Klabin S.A.'},
 {'code': 'MSPA3', 'name': 'Cia Melhoramentos De Sao Paulo'},
 {'code': 'MSPA4', 'name': 'Cia Melhoramentos De Sao Paulo'},
 {'code': 'NEMO3', 'name': 'Suzano Holding S.A.'},
 {'code': 'NEMO5', 'name': 'Suzano Holding S.A.'},
 {'code': 'NEMO6', 'name': 'Suzano Holding S.A.'},
 {'code': 'RANI3', 'name': 'Irani Papel E Embalagem S.A.'},
 {'code': 'RANI4', 'name': 'Irani Papel E Embalagem S.A.'},
 {'code': 'SUZB3', 'name': 'Suzano S.A.'},
 {'code': 'SNSY3', 'name': 'Sansuy S.A. Industria De Plasticos'},
 {'code': 'SNSY5', 'name': 'Sansuy S.A. Industria De Plasticos'},
 {'code': 'SNSY6', 'name': 'Sansuy S.A. Industria De Plasticos'},
 {'code': 'BRAP3', 'name': 'Bradespar S.A.'},
 {'code': 'BRAP4', 'name': 'Bradespar S.A.'},
 {'code': 'LTEL', 'name': 'Litel Participacoes S.A.'},
 {'code': 'LTLA', 'name': 'Litela Participações S.A.'},
 {'code': 'MMXM11', 'name': 'Mmx Mineracao E Metalicos S.A.'},
 {'code': 'MMXM3', 'name': 'Mmx Mineracao E Metalicos S.A.'},
 {'code': 'VALE3', 'name': 'Vale S.A.'},
 {'code': 'FHER3', 'name': 'Fertilizantes Heringer S.A.'},
 {'code': 'NUTR3', 'name': 'Nutriplant Industria E Comercio S.A.'},
 {'code': 'BRKM3', 'name': 'Braskem S.A.'},
 {'code': 'BRKM5', 'name': 'Braskem S.A.'},
 {'code': 'BRKM6', 'name': 'Braskem S.A.'},
 {'code': 'GPCP3', 'name': 'Gpc Participacoes S.A.'},
 {'code': 'GPCP4', 'name': 'Gpc Participacoes S.A.'},
 {'code': 'CRPG3', 'name': 'Tronox Pigmentos Do Brasil S.A.'},
 {'code': 'CRPG5', 'name': 'Tronox Pigmentos Do Brasil S.A.'},
 {'code': 'CRPG6', 'name': 'Tronox Pigmentos Do Brasil S.A.'},
 {'code': 'UNIP3', 'name': 'Unipar Carbocloro S.A.'},
 {'code': 'UNIP5', 'name': 'Unipar Carbocloro S.A.'},
 {'code': 'UNIP6', 'name': 'Unipar Carbocloro S.A.'},
 {'code': 'PMAM3', 'name': 'Paranapanema S.A.'},
 {'code': 'MGEL3', 'name': 'Mangels Industrial S.A.'},
 {'code': 'MGEL4', 'name': 'Mangels Industrial S.A.'},
 {'code': 'PATI3', 'name': 'Panatlantica S.A.'},
 {'code': 'PATI4', 'name': 'Panatlantica S.A.'},
 {'code': 'TKNO3', 'name': 'Tekno S.A. - Industria E Comercio'},
 {'code': 'TKNO4', 'name': 'Tekno S.A. - Industria E Comercio'},
 {'code': 'CSNA3', 'name': 'Cia Siderurgica Nacional'},
 {'code': 'FESA3', 'name': 'Cia Ferro Ligas Da Bahia - Ferbasa'},
 {'code': 'FESA4', 'name': 'Cia Ferro Ligas Da Bahia - Ferbasa'},
 {'code': 'GGBR3', 'name': 'Gerdau S.A.'},
 {'code': 'GGBR4', 'name': 'Gerdau S.A.'},
 {'code': 'GOAU3', 'name': 'Metalurgica Gerdau S.A.'},
 {'code': 'GOAU4', 'name': 'Metalurgica Gerdau S.A.'},
 {'code': 'USIM3', 'name': 'Usinas Sid De Minas Gerais S.A.-Usiminas'},
 {'code': 'USIM5', 'name': 'Usinas Sid De Minas Gerais S.A.-Usiminas'},
 {'code': 'USIM6', 'name': 'Usinas Sid De Minas Gerais S.A.-Usiminas'},
 {'code': 'ALEF', 'name': 'Alef S.A.'},
 {'code': 'ATOM3', 'name': 'Atom Empreendimentos E Participacoes S.A.'},
 {'code': 'BETP', 'name': 'Betapart Participacoes S.A.'},
 {'code': 'CABI', 'name': 'Cabinda Participacoes S.A.'},
 {'code': 'CACO', 'name': 'Caconde Participacoes S.A.'},
 {'code': 'CMSA3', 'name': 'Cims S.A.'},
 {'code': 'CMSA4', 'name': 'Cims S.A.'},
 {'code': 'FIGE3', 'name': 'Investimentos Bemge S.A.'},
 {'code': 'FIGE4', 'name': 'Investimentos Bemge S.A.'},
 {'code': 'JBDU3', 'name': 'Industrias J B Duarte S.A.'},
 {'code': 'JBDU4', 'name': 'Industrias J B Duarte S.A.'},
 {'code': 'MAPT3', 'name': 'Cemepe Investimentos S.A.'},
 {'code': 'MAPT4', 'name': 'Cemepe Investimentos S.A.'},
 {'code': 'OPGM', 'name': 'Gama Participacoes S.A.'},
 {'code': 'OPHE', 'name': 'Opportunity Energia E Participacoes S.A.'},
 {'code': 'OPSE', 'name': 'Sudeste S.A.'},
 {'code': 'OPTS', 'name': 'Sul 116 Participacoes S.A.'},
 {'code': 'PPAR3', 'name': 'Polpar S.A.'},
 {'code': 'PRPT', 'name': 'Prompt Participacoes S.A.'},
 {'code': 'QVQP', 'name': '524 Participacoes S.A.'},
 {'code': 'LUPA3', 'name': 'Lupatech S.A.'},
 {'code': 'OSXB3', 'name': 'Osx Brasil S.A.'},
 {'code': 'BRDT3', 'name': 'Petrobras Distribuidora S/A'},
 {'code': 'CSAN3', 'name': 'Cosan S.A.'},
 {'code': 'DMMO3', 'name': 'Dommo Energia S.A.'},
 {'code': 'ENAT3', 'name': 'Enauta Participacoes S.A.'},
 {'code': 'PETR3', 'name': 'Petroleo Brasileiro S.A. Petrobras'},
 {'code': 'PETR4', 'name': 'Petroleo Brasileiro S.A. Petrobras'},
 {'code': 'PRIO3', 'name': 'Petro Rio S.A.'},
 {'code': 'RPMG3', 'name': 'Refinaria De Petroleos Manguinhos S.A.'},
 {'code': 'RRRP3', 'name': '3r Petroleum Óleo E Gás S.A'},
 {'code': 'UGPA3', 'name': 'Ultrapar Participacoes S.A.'},
 {'code': 'DMVF3', 'name': 'D1000 Varejo Farma Participações S.A.'},
 {'code': 'HYPE3', 'name': 'Hypera S.A.'},
 {'code': 'PFRM3', 'name': 'Profarma Distrib Prod Farmaceuticos S.A.'},
 {'code': 'PGMN3', 'name': 'Empreendimentos Pague Menos S.A.'},
 {'code': 'PNVL3', 'name': 'Dimed S.A. Distribuidora De Medicamentos'},
 {'code': 'PNVL4', 'name': 'Dimed S.A. Distribuidora De Medicamentos'},
 {'code': 'RADL3', 'name': 'Raia Drogasil S.A.'},
 {'code': 'BALM3', 'name': 'Baumer S.A.'},
 {'code': 'BALM4', 'name': 'Baumer S.A.'},
 {'code': 'LMED3',
  'name': 'Lifemed Industrial Equip. De Art. Med. Hosp. S.A.'},
 {'code': 'BIOM3', 'name': 'Biomm S.A.'},
 {'code': 'NRTQ3', 'name': 'Nortec Quimica S.A.'},
 {'code': 'OFSA3', 'name': 'Ouro Fino Saude Animal Participacoes S.A.'},
 {'code': 'AALR3', 'name': 'Centro De Imagem Diagnosticos S.A.'},
 {'code': 'ADHM3', 'name': 'Advanced Digital Health Medicina Preventiva S.A.'},
 {'code': 'DASA3', 'name': 'Diagnosticos Da America S.A.'},
 {'code': 'FLRY3', 'name': 'Fleury S.A.'},
 {'code': 'GNDI3', 'name': 'Notre Dame Intermedica Participacoes Sa'},
 {'code': 'HAPV3', 'name': 'Hapvida Participacoes E Investimentos SA'},
 {'code': 'ODPV3', 'name': 'Odontoprev S.A.'},
 {'code': 'PARD3', 'name': 'Instituto Hermes Pardini S.A.'},
 {'code': 'QUAL3',
  'name': 'Qualicorp Consultoria E Corretora De Seguros S.A.'},
 {'code': 'RDOR3', 'name': 'Rede Dor São Luiz S.A.'},
 {'code': 'POSI3', 'name': 'Positivo Tecnologia S.A.'},
 {'code': 'BRQB3', 'name': 'Brq Solucoes Em Informatica S.A.'},
 {'code': 'CASH3', 'name': 'MéLiuz S.A.'},
 {'code': 'ENJU3', 'name': 'Enjoei.Com.Br Atividades De Internet S.A.'},
 {'code': 'LINX3', 'name': 'Linx S.A.'},
 {'code': 'LWSA3', 'name': 'Locaweb Servicos De Internet S.A.'},
 {'code': 'NGRD3', 'name': 'Neogrid Participacoes S.A.'},
 {'code': 'QUSW3', 'name': 'Quality Software S.A.'},
 {'code': 'SQIA3', 'name': 'Sinqia S.A.'},
 {'code': 'TOTS3', 'name': 'Totvs S.A.'},
 {'code': 'AMBP3', 'name': 'Ambipar Participacoes E Empreendimentos S/A'},
 {'code': 'CASN3', 'name': 'Cia Catarinense De Aguas E Saneam.-Casan'},
 {'code': 'CASN4', 'name': 'Cia Catarinense De Aguas E Saneam.-Casan'},
 {'code': 'CSMG3', 'name': 'Cia Saneamento De Minas Gerais-Copasa MG'},
 {'code': 'IGSN3', 'name': 'Igua Saneamento S.A.'},
 {'code': 'SAPR11', 'name': 'Cia Saneamento Do Parana - Sanepar'},
 {'code': 'SAPR3', 'name': 'Cia Saneamento Do Parana - Sanepar'},
 {'code': 'SAPR4', 'name': 'Cia Saneamento Do Parana - Sanepar'},
 {'code': 'SBSP3', 'name': 'Cia Saneamento Basico Est Sao Paulo'},
 {'code': 'AESL', 'name': 'RGE Sul Distribuidora de Energia S.A.'},
 {'code': 'AFLT3', 'name': 'Afluente Transmissao De Energia Eletrica S/A'},
 {'code': 'ALUP11', 'name': 'Alupar Investimento S/A'},
 {'code': 'ALUP3', 'name': 'Alupar Investimento S/A'},
 {'code': 'ALUP4', 'name': 'Alupar Investimento S/A'},
 {'code': 'CBEE3', 'name': 'Ampla Energia E Servicos S.A.'},
 {'code': 'CEBR3', 'name': 'Cia Energetica De Brasilia'},
 {'code': 'CEBR5', 'name': 'Cia Energetica De Brasilia'},
 {'code': 'CEBR6', 'name': 'Cia Energetica De Brasilia'},
 {'code': 'CEEB3', 'name': 'Cia Eletricidade Est. Da Bahia - Coelba'},
 {'code': 'CEEB5', 'name': 'Cia Eletricidade Est. Da Bahia - Coelba'},
 {'code': 'CEEB6', 'name': 'Cia Eletricidade Est. Da Bahia - Coelba'},
 {'code': 'CEED3', 'name': 'Cia Estadual De Distrib Ener Elet-Ceee-D'},
 {'code': 'CEED4', 'name': 'Cia Estadual De Distrib Ener Elet-Ceee-D'},
 {'code': 'CEPE3', 'name': 'Cia Energetica De Pernambuco - Celpe'},
 {'code': 'CEPE5', 'name': 'Cia Energetica De Pernambuco - Celpe'},
 {'code': 'CEPE6', 'name': 'Cia Energetica De Pernambuco - Celpe'},
 {'code': 'CESP3', 'name': 'Cesp - Cia Energetica De Sao Paulo'},
 {'code': 'CESP5', 'name': 'Cesp - Cia Energetica De Sao Paulo'},
 {'code': 'CESP6', 'name': 'Cesp - Cia Energetica De Sao Paulo'},
 {'code': 'CLSC3', 'name': 'Centrais Elet De Santa Catarina S.A.'},
 {'code': 'CLSC4', 'name': 'Centrais Elet De Santa Catarina S.A.'},
 {'code': 'CMIG3', 'name': 'Cia Energetica De Minas Gerais - Cemig'},
 {'code': 'CMIG4', 'name': 'Cia Energetica De Minas Gerais - Cemig'},
 {'code': 'COCE3', 'name': 'Cia Energetica Do Ceara - Coelce'},
 {'code': 'COCE5', 'name': 'Cia Energetica Do Ceara - Coelce'},
 {'code': 'COCE6', 'name': 'Cia Energetica Do Ceara - Coelce'},
 {'code': 'CPFE3', 'name': 'Cpfl Energia S.A.'},
 {'code': 'CPLE3', 'name': 'Cia Paranaense De Energia - Copel'},
 {'code': 'CPLE5', 'name': 'Cia Paranaense De Energia - Copel'},
 {'code': 'CPLE6', 'name': 'Cia Paranaense De Energia - Copel'},
 {'code': 'CPRE3', 'name': 'Cpfl Energias Renovaveis S.A.'},
 {'code': 'CSRN3', 'name': 'Cia Energetica Do Rio Gde Norte - Cosern'},
 {'code': 'CSRN5', 'name': 'Cia Energetica Do Rio Gde Norte - Cosern'},
 {'code': 'CSRN6', 'name': 'Cia Energetica Do Rio Gde Norte - Cosern'},
 {'code': 'EEEL3', 'name': 'Cia Estadual Ger.Trans.Ener.Elet-Ceee-Gt'},
 {'code': 'EEEL4', 'name': 'Cia Estadual Ger.Trans.Ener.Elet-Ceee-Gt'},
 {'code': 'EGIE3', 'name': 'Engie Brasil Energia S.A.'},
 {'code': 'EKTR3', 'name': 'Elektro Redes S.A.'},
 {'code': 'EKTR4', 'name': 'Elektro Redes S.A.'},
 {'code': 'ELET3', 'name': 'Centrais Elet Bras S.A. - Eletrobras'},
 {'code': 'ELET5', 'name': 'Centrais Elet Bras S.A. - Eletrobras'},
 {'code': 'ELET6', 'name': 'Centrais Elet Bras S.A. - Eletrobras'},
 {'code': 'EMAE3', 'name': 'Emae - Empresa Metrop.Aguas Energia S.A.'},
 {'code': 'EMAE4', 'name': 'Emae - Empresa Metrop.Aguas Energia S.A.'},
 {'code': 'ENBR3', 'name': 'Edp - Energias Do Brasil S.A.'},
 {'code': 'ENEV3', 'name': 'Eneva S.A'},
 {'code': 'ENGI11', 'name': 'Energisa S.A.'},
 {'code': 'ENGI3', 'name': 'Energisa S.A.'},
 {'code': 'ENGI4', 'name': 'Energisa S.A.'},
 {'code': 'ENMT3',
  'name': 'Energisa Mato Grosso-Distribuidora De Energia S/A'},
 {'code': 'ENMT4',
  'name': 'Energisa Mato Grosso-Distribuidora De Energia S/A'},
 {'code': 'EQMA', 'name': 'Equatorial Maranhão Distribuidora De Energia S.A.'},
 {'code': 'EQPA3', 'name': 'Equatorial Para Distribuidora De Energia S.A.'},
 {'code': 'EQPA5', 'name': 'Equatorial Para Distribuidora De Energia S.A.'},
 {'code': 'EQPA6', 'name': 'Equatorial Para Distribuidora De Energia S.A.'},
 {'code': 'EQPA7', 'name': 'Equatorial Para Distribuidora De Energia S.A.'},
 {'code': 'EQTL3', 'name': 'Equatorial Energia S.A.'},
 {'code': 'GEPA3', 'name': 'Rio Paranapanema Energia S.A.'},
 {'code': 'GEPA4', 'name': 'Rio Paranapanema Energia S.A.'},
 {'code': 'GPAR3', 'name': 'Cia Celg De Participacoes - Celgpar'},
 {'code': 'LIGT3', 'name': 'Light S.A.'},
 {'code': 'LIPR3', 'name': 'Eletrobras Participacoes S.A. - Eletropar'},
 {'code': 'NEOE3', 'name': 'Neoenergia S.A.'},
 {'code': 'OMGE3', 'name': 'Omega Geracao S.A.'},
 {'code': 'PRMN', 'name': 'Produtores Energet.De Manso S.A.- Proman'},
 {'code': 'REDE3', 'name': 'Rede Energia Participacoes S.A.'},
 {'code': 'RNEW11', 'name': 'Renova Energia S.A.'},
 {'code': 'RNEW3', 'name': 'Renova Energia S.A.'},
 {'code': 'RNEW4', 'name': 'Renova Energia S.A.'},
 {'code': 'STKF3', 'name': 'Statkraft Energias Renovaveis S.A.'},
 {'code': 'TAEE11', 'name': 'Trans. Alianca De Energia Eletrica S.A.'},
 {'code': 'TAEE3', 'name': 'Trans. Alianca De Energia Eletrica S.A.'},
 {'code': 'TAEE4', 'name': 'Trans. Alianca De Energia Eletrica S.A.'},
 {'code': 'TIET11', 'name': 'Aes Tiete Energia SA'},
 {'code': 'TIET3', 'name': 'Aes Tiete Energia SA'},
 {'code': 'TIET4', 'name': 'Aes Tiete Energia SA'},
 {'code': 'TRPL3',
  'name': 'Cteep - Cia Transmissao Energia Eletrica Paulista'},
 {'code': 'TRPL4',
  'name': 'Cteep - Cia Transmissao Energia Eletrica Paulista'},
 {'code': 'UPKP', 'name': 'Uptick Participacoes S.A.'},
 {'code': 'CEGR3', 'name': 'Cia Distrib De Gas Do Rio De Janeiro-Ceg'},
 {'code': 'CGAS3', 'name': 'Cia Gas De Sao Paulo - Comgas'},
 {'code': 'CGAS5', 'name': 'Cia Gas De Sao Paulo - Comgas'}]

    #return '''<h1>O código é: {}</h1>'''.format(codigo)
    #return jsonify({'Dados para graficos' : f'{parsed}'})
    #return jsonify(result)
    return jsonify(parsed)

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)
